#!/usr/bin/env node
// Commit message format (RULES.md → Git): "area: what changed"
//   area   = one of the project areas below
//   subject = lower-case start, ≤ 72 chars, no trailing period
const fs = require('fs');

const AREAS = ['core', 'api', 'db', 'web', 'infra', 'docs', 'data', 'test', 'chore', 'checks', 'deps', 'fix'];
const file = process.argv[2];
const first = fs.readFileSync(file, 'utf8').split(/\r?\n/).find(l => l.trim() && !l.startsWith('#')) || '';

// merge / revert / fixup messages are generated by git — let them through
if (/^(Merge|Revert|fixup!|squash!)/.test(first)) process.exit(0);

const m = first.match(/^([a-z]+)(\([a-z0-9-]+\))?: (.+)$/);
const errors = [];
if (!m) errors.push('Format must be "area: what changed", e.g. "core: merge duplicate reports, failure wins".');
else {
  if (!AREAS.includes(m[1])) errors.push(`Unknown area "${m[1]}". Use one of: ${AREAS.join(', ')}.`);
  if (/^[A-Z]/.test(m[3])) errors.push('Start the subject in lower case.');
  if (m[3].endsWith('.')) errors.push('No trailing period.');
}
if (first.length > 72) errors.push(`First line is ${first.length} chars; keep it ≤ 72.`);

if (errors.length) {
  console.error('\nCommit message rejected:\n  ' + first + '\n' + errors.map(e => '  ✗ ' + e).join('\n') + '\n');
  process.exit(1);
}
